//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.MagisterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MagisterService.IMagisterBattle")]
    public interface IMagisterBattle {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagisterBattle/LogIn", ReplyAction="http://tempuri.org/IMagisterBattle/LogInResponse")]
        string LogIn(string name, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagisterBattle/LogIn", ReplyAction="http://tempuri.org/IMagisterBattle/LogInResponse")]
        System.Threading.Tasks.Task<string> LogInAsync(string name, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMagisterBattleChannel : TestClient.MagisterService.IMagisterBattle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MagisterBattleClient : System.ServiceModel.ClientBase<TestClient.MagisterService.IMagisterBattle>, TestClient.MagisterService.IMagisterBattle {
        
        public MagisterBattleClient() {
        }
        
        public MagisterBattleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MagisterBattleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MagisterBattleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MagisterBattleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LogIn(string name, string pass) {
            return base.Channel.LogIn(name, pass);
        }
        
        public System.Threading.Tasks.Task<string> LogInAsync(string name, string pass) {
            return base.Channel.LogInAsync(name, pass);
        }
    }
}
